### ISSUE TITLE
Enabling SonarQubeCloud-Analysis on Pull-Request

### ISSUE THREAD

**Issue by bruderj15** [kadai-io/kadai#515]
SonarQubeCloud has updated their plans, restricting the old free plan to only allow analysises on the main branch of a repository.
Users that registered with the former plan - now called _Legacy Plan_ - can still analyze all branches.
However, according to their [documentation](https://docs.sonarsource.com/sonarqube-cloud/administering-sonarcloud/managing-subscription/subscription-plans/), theses users (and organizations) will have to migrate to the new _Free Plan_ soon.

Therefore it has been proposed to upgrade this repository to the _Team Plan_, once this change takes place.
We would then let SonarQubeCloud analyze on every PR.
This would provide addtional benefit in Forks not having to set up analyses themselves.

Actually, analyzation on PR is [enabled by default](https://docs.sonarsource.com/sonarqube-cloud/improving/pull-request-analysis/).
We currently suppress it in [CI](https://github.com/kadai-io/kadai/blob/master/.github/workflows/continuous-integration.yml#L485):
```yaml
...
  upload_to_sonar:
    runs-on: ubuntu-22.04
    name: Upload SonarQube analysis to sonarcloud
    # no pull request and not on release
    if: github.head_ref == '' && !startsWith(github.ref, 'refs/tags')
    ...
```

To allow analysis for already affected (new) users, enabling analysis on PR shall be considered.
